### ISSUE TITLE
Remove `/api/search.txt` from every payload

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/website#132]
### Environment

node

### Reproduction

https://unjs.io/_payload.json

As you can see, the search content, starting by `documentCount` is in the payload.

### Describe the bug

This is an issue since it's heavy content and it's size will increase. For every page, end user will load this content, even if he does not use the search.

**Comment by pi0** [comment]
Is this coming from content module?

**Comment by Barbapapazes** [comment]
> Is this coming from content module?

Nop, it's because I load the `/api/search.txt` in the server and the content is added to the payload.
