### ISSUE TITLE
Docs shows as empty

### ISSUE THREAD

**Issue by ojvribeiro** [unjs/website#135]
### Environment

Tested locally on:

------------------------------
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.7.1
- CLI Version:      3.8.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.7.5
- Builder:          -
- User Config:      app, runtimeConfig, modules, experimental, css, nitro, content, unocss, site, sitemap, routeRules, devtools
- Runtime Modules:  @nuxt/content@2.8.2, @vueuse/nuxt@10.4.1, @unocss/nuxt@0.55.7, nuxt-simple-robots@3.1.2, nuxt-simple-sitemap@3.2.7, nuxt-schema-org@2.2.0, @nuxthq/studio@0.14.1, @nuxtjs/plausible@0.2.3
- Build Modules:    -
------------------------------

### Reproduction

The problem shows on https://unjs.io/ website as well as if I run it locally.

- Go to https://unjs.io/packages
- Click on any package
- See the doc empty message

![image](https://github.com/unjs/website/assets/8026741/8bf1a42d-e9ac-4a5b-b2e9-3527ebe3b974)

### Describe the bug

All packages show an empty message in https://unjs.io/

![image](https://github.com/unjs/website/assets/8026741/d3feefc0-745a-4e5b-bb0a-a13401650389)
![image](https://github.com/unjs/website/assets/8026741/36adb537-57e1-4850-9c56-49f380758586)

**Comment by Barbapapazes** [comment]
Hello,

Thanks for reporting this! We have to fill this!
