### ISSUE TITLE
Improving Visibility of Code Snippets in Light Mode

### ISSUE THREAD

**Issue by jwanner83** [unjs/website#261]
### Environment

Reproduced in `Firefox 122.0 (64-Bit)` and `Chrome 121.0.6167.85 (Official Build) (arm64)`, both on `macOS 14.2.1`.

### Reproduction

1. Enable Light Mode in the Footer of the page.
2. Visit this URL: https://unjs.io/packages/c12#usage
3. Try to read the code in the code snippets. 

### Describe the bug

If the page is viewed in light mode, the code snippets are not really visible because the text color is to close to the background color.

**Comment by jwanner83** [comment]
I wanted to fix the issue by myself but as I forked the site and run it locally, the error seems to be already fixed. Is production behind of the main branch?

Local:
![Bildschirmfoto 2024-01-30 um 15 57 43](https://github.com/unjs/website/assets/38656104/2fe349d4-b60c-45e4-89d7-36384492262f)

Production:
![Bildschirmfoto 2024-01-30 um 15 30 19](https://github.com/unjs/website/assets/38656104/8f167d9b-5c09-40a1-ae89-1fd4869e4530)

**Comment by Barbapapazes** [comment]
should be fixed in some minutes.
