### ISSUE TITLE
UNJS WEBSITE IS DOWN🚨

### ISSUE THREAD

**Issue by moshetanzer** [unjs/website#330]
### Environment

Web

### Reproduction

UNJS.io

### Describe the bug

Hi @pi0,

think undocs update may have broken unjs website. It displays nothing, though resolves.

**Comment by pi0** [comment]
This repo does not depends on undocs but yeah I also noticed this to @Barbapapazes seems there is something wrong.

**Comment by pi0** [comment]
since last commit fixed

**Comment by moshetanzer** [comment]
Great. 👍

**Comment by Barbapapazes** [comment]
Oups sorry for that! You was quick! Will investigate to found a way to avoid this type of issues (related to a bad indentation in a yml file)
