### ISSUE TITLE
Puzzle transition bug 

### ISSUE THREAD

**Issue by enkot** [unjs/website#37]
### Environment

Chrome 115.0.5790.170 (Official Build) (arm64)

### Reproduction

[Unleash your Full Potential · UnJS.webm](https://github.com/unjs/website/assets/10506522/e19eab92-f5ab-4f72-bae5-2c088a3e263b)

### Describe the bug

In some mouse positions puzzle starts to jump between states.

### Additional context

By the way, great design, love it! ❤️

**Comment by Barbapapazes** [comment]
Hello,

Yeah, I know but I don't really know how I could fix this! 🤔

It happens because the square containing the puzzle (which is hover) will shrink when parts come together.

**Comment by cpreston321** [comment]
@Barbapapazes to get around this would it be better to handle it on scroll vs on hover ? Just an option. 

Scroll down -> increments animation combining the puzzle
Scoll back up -> increments animation out to default state.
