### ISSUE TITLE
Rework the package page

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/website#76]
- [x] #102
- [ ] #104
- [x] #100

**Comment by igorjacauna** [comment]
Hello!

Maybe add the `README.md` content from package in page body using the [ungh](https://github.com/unjs/ungh#reposownernamefilesbranchpath)?

**Comment by igorjacauna** [comment]
Hello! 

I drafted a [PR](https://github.com/unjs/website/pull/131) to collaborate. But I need help with two points:

1. The title and description from `README.md` in packate repo make redundant in page. Any ideas how to slice this from `README.md` content to keep the title and description that already exsists? I thought of something like `slice` the `children` the first item in array from fetch in `api/reame-parser`. 
2. Using `useAsyncData` only fetch in SSR not in client side. So, when navigating in preview mode, the content is not showing, only when refresh the page.

**Comment by Barbapapazes** [comment]
> Hello!
> 
> I drafted a [PR](https://github.com/unjs/website/pull/131) to collaborate. But I need help with two points:
> 
> 1. The title and description from `README.md` in packate repo make redundant in page. Any ideas how to slice this from `README.md` content to keep the title and description that already exsists? I thought of something like `slice` the `children` the first item in array from fetch in `api/reame-parser`.
> 2. Using `useAsyncData` only fetch in SSR not in client side. So, when navigating in preview mode, the content is not showing, only when refresh the page.

Hello, thanks you so much for taking time to help! I've created another PR because I encountered a lot of issue which with the build model and with Nuxt Content (like https://github.com/nuxt/content/pull/2280). To remove the title, I use the AST of the package.

In order to have the correct behavior when navigating, I completely move to a static build (using nitro: { static }).
