### ISSUE TITLE
Payload is too heavy (navigation, keys...)

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/website#79]
In the page payload, all the navigation is in it. So every packages are in every pages which is a lot of data for nothing.

I need to review all the fetch in order to remove unused content.

**Comment by Barbapapazes** [comment]
Maybe, it's not the navigation but the generated content for the search. And I'm no sure to completely understand how the payload extraction works. Do you have any docs about this feature?

**Comment by danielroe** [comment]
Anything returned from `useAsyncData` or `useFetch` gets put in the payload and extracted into a separate file.

**Comment by Barbapapazes** [comment]
> Anything returned from `useAsyncData` or `useFetch` gets put in the payload and extracted into a separate file when the page is prerendered.

And is it fetch by the application? How this file is used?

**Comment by danielroe** [comment]
yes, this will be fetched as a single file instead of rerunning the asyncData/fetch request. You can optimise with the `transform` hook in useFetch to prune unused properties, for example.
